name: 'Manage stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '50 13 * * *'
jobs:
  stale:
    uses: Islandora-Devops/.github/.github/workflows/stale.yaml@main
    secrets: inherit
